# Generated by Django 5.2.7 on 2025-10-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_product_image_product_stock_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronica', 'Electrónica'), ('ropa', 'Ropa'), ('deportes', 'Deportes'), ('hogar', 'Hogar'), ('accesorios', 'Accesorios')], default='electronica', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Nuevo'), ('used', 'Usado')], default='new', max_length=4),
        ),
    ]
