# Generated by Django 5.2.7 on 2025-11-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_product_category_product_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bebidas', 'Bebidas'), ('almacen', 'Almacén'), ('frescos', 'Frescos'), ('lacteos', 'Lácteos'), ('carnes', 'Carnes y Pescados'), ('verduras', 'Frutas y Verduras'), ('panaderia', 'Panadería'), ('limpieza', 'Limpieza'), ('perfumeria', 'Perfumería'), ('congelados', 'Congelados'), ('snacks', 'Snacks y Golosinas'), ('pastas', 'Pastas')], default='almacen', max_length=20),
        ),
    ]
