# Generated by Django 5.2.5 on 2025-11-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='category',
            field=models.CharField(choices=[('almacen', 'Almacén'), ('bebidas', 'Bebidas'), ('lacteos', 'Lácteos y Huevos'), ('carnes', 'Carnes y Pescados'), ('frutas', 'Frutas y Verduras'), ('panaderia', 'Panadería'), ('limpieza', 'Limpieza'), ('higiene', 'Higiene Personal'), ('congelados', 'Congelados'), ('snacks', 'Snacks y Golosinas'), ('desayuno', 'Desayuno y Cereales')], default='almacen', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='condition',
            field=models.CharField(choices=[('new', 'Nuevo'), ('used', 'Usado')], default='new', max_length=10, verbose_name='Condición'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca'),
        ),
    ]
