# Generated by Django 5.2.6 on 2025-11-10 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='title',
        ),
    ]
