# Generated by Django 5.2.6 on 2025-11-10 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_rename_descripcion_producto_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='title',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='price',
            new_name='precio',
        ),
    ]
